config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root to: "items#index"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :items
  get 'my_items', to: 'items#my_items', as: 'my_items'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: [:create], param: :chatroom_id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages





  def other_user_email(current_user)
    other_user = users.joins(:chatroom_users).where.not(id: current_user.id).first
    other_user&.email
  end



end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :reward, numericality: true, allow_blank: true
  validates :status, inclusion: { in: [0, 1, 2, 3, 100] }, presence: true
  attribute :source, :integer, default: 0
  validates :name, presence: true
  validates :description, length: { maximum: 150 }
  validates :date, presence: true

  # for Geocoder
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: %i[index my_items], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: %i[index my_items], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @user = current_user
    @chatrooms = policy_scope(@user.chatrooms).order(created_at: :desc)
  end

  def show
    @chatroom = find_or_create_chatroom
    authorize @chatroom, policy_class: ChatroomPolicy
    @messages = @chatroom.messages
    @message = Message.new
    @message.user = current_user
    @other_user = User.find(@other_user_id) if @other_user_id
  end

  private

  def find_or_create_chatroom
    @user_id = current_user.id.to_i
    @other_user_id = params[:other_user_id].to_i if params[:other_user_id].present?
    @other_user = User.find(@other_user_id) if @other_user_id

    if @other_user_id
      chatroom = Chatroom.joins(:chatroom_users)
                          .where(chatrooms: { name: generate_chatroom_name(@user_id, @other_user_id) })
                          .where(chatroom_users: { user_id: [@user_id, @other_user_id] })
                          .group('chatrooms.id')
                          .having('COUNT(DISTINCT chatroom_users.user_id) = 2')
                          .first

      chatroom ||= Chatroom.create(name: generate_chatroom_name(@user_id, @other_user_id))
      create_chatroom_user(chatroom, @user_id)
      create_chatroom_user(chatroom, @other_user_id)
    else
      chatroom = Chatroom.find(params[:id])
    end

    chatroom
  end

  def generate_chatroom_name(user_id, other_user_id)
    [user_id, other_user_id].sort.join("_")
  end

  def create_chatroom_user(chatroom, user_id)
    chatroom.chatroom_users.find_or_create_by(user_id: user_id)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @chatroom = Chat
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  def index
    @items = policy_scope(Item).order(date: :asc).all
    @lost_marker_items = policy_scope(Item).order(date: :asc).where(status: 0)
    @markers = @lost_marker_items.geocoded.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        status: item.status,
        info_window_html: render_to_string(partial: "shared/info_window", locals: { item: }),
        marker_html: render_to_string(partial: "marker", locals: { item: })
      }
    end
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item

    if @item.save
      redirect_to item_path(@item), notice: 'Showing Possible matches.'
    else
      render :new
    end
  end

  def show
    authorize @item
    @marker = {
      lat: @item.latitude,
      lng: @item.longitude
    }
    # Initialize @potential_matches
    @potential_matches = []
    # Find potential matches within 3 km distance
    @potential_matches = Item.near([@item.latitude, @item.longitude], 30000, units: :mi)
                         .where.not(user_id: current_user.id)


    @markers = @potential_matches.geocoded.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        status: item.status,
        info_window_html: render_to_string(partial: "shared/info_window", locals: { item: }),
        marker_html: render_to_string(partial: "marker", locals: { item: })
      }
    end
  end


  def edit
    authorize @item
  end

  def update
    authorize @item
    if @item.update(item_params)
      redirect_to my_items_path, notice: "Item was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize @item
    @item.destroy
    redirect_to my_items_path, notice: 'Item deleted successfully.'
  end

  def my_items
    @items = policy_scope(Item).where(user: current_user)
  end

  private


  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:user_id, :status, :name, :date, :location, :reward, :description, :image)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])

    if @chatroom
      @message = @chatroom.messages.new(message_params)
      authorize @message
      @message.user = current_user

      if @message.save
        ChatroomChannel.broadcast_to(
          @chatroom,
          render_to_string(partial: "message", locals: {message: @message})
        )
        head :ok
      else
        redirect_to chatroom_path(@chatroom), alert: 'Failed to send message.'
      end
    else
      redirect_to root_path, alert: 'Chatroom or other user not found.'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<h1 class=custom-h1>Active Chats</h1>

<div class= "chats-list">
  <ul class="list-group">
    <% @chatrooms.each do |chatroom| %>
      <% other_user_email = chatroom.other_user_email(current_user) %>
      <% other_user = User.find_by(email: other_user_email) %>
        <li class="list-group-item">
          <%= link_to chatroom_path(chatroom, other_user_id: other_user.id), class: "stretched-link" do %>
            <h2 class="mb-1" style="color: #393E46;">
              <%= other_user.email.split("@").first.capitalize %>
            </h2>
          <% end %>
        </li>
    <% end %>
  </ul>
</div>

app/views/chatrooms/show.html.erb
<h1 class='custom-h1'>Chatting with - <%= @other_user&.email.split("@").first.capitalize %> </h1>


<div id="messages-container"
     data-controller="chatroom-subscription"
     data-chatroom-subscription-chatroom-id-value="<%=@chatroom.id%>"
>
  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>



  <div id="new-message-form">
    <%= simple_form_for([@chatroom, Message.new], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" } }) do |form| %>
      <%= form.input :body, as: :text, input_html: { rows: 3 }, label: false, placeholder: 'Type your message...' %>
        <div class="d-flex justify-content-between">
          <%= form.button :submit, 'Send Message', class: 'btn btn-primary' %>
          <%= link_to "Item Reunited", root_path, class: 'btn btn-primary' %>
        </div>
    <% end %>
    <%# <%= link_to "End Chat", root_path, class: 'btn btn-primary' %>
  </div>

</div>

app/views/items/_marker.html.erb
<% if item[:status] == 0 %>
  <%= image_tag "lost_item_marker.png", height: 30, width: 30, alt: "Logo" %>
<% elsif item[:status] == 1 %>
  <%= image_tag "found_item_marker.png", height: 30, width: 30, alt: "Logo" %>
<% end %>

app/views/items/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-4">
    <div class="card mt-3 shadow">
      <div class="card-body">
        <h2 class="card-title">Edit Item</h2>
        <%= simple_form_for @item do |f| %>
          <div class="form-group mb-2">
            <%= f.input :name, label: "Item Name" %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Description" %>
            <%= f.text_area :description, rows: 3, class: "form-control" %>
          </div>
            <div class="form-group mt-3">
            <%= f.label :date, "Date" %>
            <%= f.date_field :date, class: "form-control", max: Date.current.to_s %>
          </div>

          <div class="form-group" id="image-field" >
            <%= f.input :image, as: :file %>
          </div>

          <div class="text-center">
            <%= f.button :submit, "Submit", class: "btn btn-primary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<%# code for dov which contains the javascript controller and the some key page styling%>
<div data-controller="hide-function" class="index-page-map">
  <div class="button-alignment-index" style="justify-content: center;">
    <%# code for lost & found item reporting button  %>
    <div class="row mx-1 mb-3  flex-column align-items-center ">
      <div class="d-flex justify-content-center col-md-3 ">
        <div class="col-xs-3">
          <div class="text-center mx-3">
            <%= link_to "Report Item", new_item_path, class: "btn btn-info " %>
          </div>
        </div>
      </div>
    </div>

    <%# code for button which hides elements %>
    <div class="row mx-1 mb-3  flex-column align-items-center ">
      <div class="d-flex justify-content-center col-md-3 ">
        <div class="col-xs-3">
          <div class="text-center mx-3">
            <button  data-action="click->hide-function#hide" data-hide-function-target="button" type="button" class="btn btn-primary"> Hide Map </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# code for mapbox map  %>
  <div data-hide-function-target="element" class="mapContainer">
    <div style="width: 100%; height: 800px;" class="col-md-3"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
  <%# code for index feed view  %>
  <div class="custom-index-container-margin">
    <div class="row mb-5 flex-column align-items-center listContainer m-4">
      <% @items.each do |item| %>
        <% if item.status == 0 %>
            <div class="card index-card-bordered col-md-3 mb-3 px-0">
              <!-- Display lost item -->
              <div class="card-header d-flex justify-content-between align-items-center" style="border-color: #EEEEEE;">
                <h5 class="card-title card-title-bold text-lost-colour mb-0">Lost <%= item.name %></h5>
                <%# <div class="card-icons">
                  <a href="#" class="message-icon"><i class="fa-solid fa-message mx-2 chat-icon"></i></a>
                </div> %>
              </div>
              <div class="card-body">
                <div class="row-lost">
                    <div class="col-md-6 text-end">
                      <% if item.image.attached? %>
                        <%= image_tag item.image, class: "card-image-fluid" %>
                      <% end %>
                    </div>
                    <div class="mt-3 col-md-6 colour: $beige">
                      <p class= "p-width"><strong>Date:</strong> <%= item.date.strftime("%B %d, %Y") %></p>
                      <p class= "p-width"><strong>Location:</strong> <%= item.location %></p>
                      <% if item.reward.present? %>
                        <p class= "p-width"><strong>Reward:</strong> $<%= item.reward %></p>
                      <% end %>
                      <p class="info">
                        <%= link_to "Info", item_path(item)%>
                        <i class="fa-solid fa-circle-info info-icon"></i>
                      </p>
                    </div>
                </div>
              </div>
            </div>
        <% elsif item.status == 1 %>
        <% if item.blur.nil? || item.blur == true %>
            <div class="card index-card-bordered col-md-3 mb-3 px-0">
              <!-- Display blurred found item -->
              <div class="card-header d-flex justify-content-between align-items-start" style="border-color: #EEEEEE;">
                <h5 class="card-title card-title-bold text-found-colour">Found <%= item.name %></h5>
                <div class="card-icons">
                </div>
              </div>
              <p class="card-text mx-5"> Hidden to prevent fraud. Report lost item to view potential matches in "My Items" .</p>
              <div class="card-body">
              <p><strong>Date:</strong> <%= item.date.strftime("%B %d, %Y") %></p>
              <p class="blurred-text"><strong>Location:</strong> <%= item.location %></p>
              </div>
            </div>
          <% else %>
            <div class="card index-card-bordered col-md-3 mb-3 px-0">
              <!-- Display found item -->
              <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="card-title text-success">Found <%= item.name %></h5>
                <div class="card-icons">
                </div>
              </div>
              <div class="card-body">
                <p><strong>Date:</strong> <%= item.date.strftime("%B %d, %Y") %></p>
                <p><strong>Location:</strong> <%= item.location %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/items/my_items.html.erb
<div class= custom-h1>
  <h1>My Listed Items</h1>
  <%# <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
  <%= link_to "Log out", destroy_user_session_path, class: 'btn btn-primary', data: {turbo_method: :delete} %>
</div>

<%# <div class="row"> %>
<% @items.each do |item| %>
  <div class="col-md-4 my-3 mx-3">
    <div class="card-body card mt-3 shadow p-3">
      <div class="card-body">
        <% if item.status == 0 %>
          <h2 class="card-title text-danger">Lost <%= item.name %></h2>
          <p class="card-text"><strong>Date:</strong> <%= item.date %></p>
          <p class="card-text"><strong>Location:</strong> <%= item.location %></p>
          <p class="card-text"><strong>Reward:</strong> <%= item.reward %></p>
          <p class="card-text"><strong>Description:</strong> <%= item.description %></p>
          <div class="d-flex justify-content-center">
            <%= link_to "Show Matches", item_path(item), class: "btn btn-primary" %>
          </div>
          <div class="d-flex justify-content-between mt-2">
            <%= link_to edit_item_path(item), class: " btn-primary" do %>
              <i class="fa-solid fa-pen-to-square fa-lg"></i>
            <% end %>
            <%= link_to item_path(item), class: " btn-primary", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } do %>
              <i class="fa-solid fa-trash fa-lg"></i>
            <% end %>
          </div>
        <% elsif item.status == 1 %>
          <h2 class="card-title text-success">Found <%= item.name %></h2>
          <p class="card-text"><strong>Date:</strong> <%= item.date %></p>
          <p class="card-text"><strong>Location:</strong> <%= item.location %></p>
          <p class="card-text"><strong>Description:</strong> <%= item.description %></p>
          <div class="d-flex justify-content-center">
            <%= link_to "Show Matches", item_path(item), class: "btn btn-primary" %>
          </div>
          <div class="d-flex justify-content-between mt-2">
            <%= link_to edit_item_path(item), class: " btn-primary" do %>
              <i class="fa-solid fa-pen-to-square fa-lg"></i>
            <% end %>
            <%= link_to item_path(item), class: " btn-primary", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } do %>
              <i class="fa-solid fa-trash fa-lg"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="justify-content-center">
  <div class="col-md-4">
    <div class="card mt-3 shadow m-3">
      <div class="report-card-body">
        <h2 class="card-title">Report Item</h2>
        <%= simple_form_for @item, html: { multipart: true } do |f| %>
          <div class="form-group">
            <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
          </div>
          <div class="form-group">
            <% [['Lost', 0], ['Found', 1]].each do |option| %>
              <div class="form-check form-check-inline">
                <%= f.radio_button :status, option[1], class: 'form-check-input mr-2 mb-4', onchange: 'toggleRewardField()' %>
                <%= label_tag "#{f.object_name}_status_#{option[1]}", option[0], class: 'form-check-label' %>
              </div>
            <% end %>
          </div>
          <div class="form-group mb-2">
            <%= f.input :name, label: "Item Name" %>
          </div>
          <div class="form-group" id="image-field" style="display: none;">
            <%= f.input :image, as: :file %>
          </div>
          <div class="form-group mt-3">
            <%= f.label :date, "Date" %>
            <%= f.date_field :date, class: "form-control", max: Date.current.to_s %>
          </div>
          <div class="form-group">
            <%= f.input :location, label: "Location" %>
          </div>
          <div class="form-group" id="reward-field" style="display: none;">
            <%= f.input :reward, input_html: { step: '0.01', min: '0', type: 'number' } %>
          </div>
          <div class="form-group">
            <%= label_tag :description, "Description" %>
            <%= text_area_tag :description, nil, rows: 3, class: "form-control" %>
          </div>
          <div class="text-center">
            <%= f.button :submit, "Submit", class: "btn btn-primary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
function toggleRewardField() {
  var rewardField = document.getElementById("reward-field");
  var imageField = document.getElementById("image-field");
  var selectedElement = document.querySelector('input[name="item[status]"]:checked');
  if (selectedElement && selectedElement.value === "0") {
    rewardField.style.display = "block";
    imageField.style.display = "block";
  } else {
    rewardField.style.display = "none";
    imageField.style.display = "none";
  }
}
// Attach event listener to the radio buttons
document.addEventListener("DOMContentLoaded", function () {
  var statusElements = document.getElementsByName("item[status]");
  for (var i = 0; i < statusElements.length; i++) {
    statusElements[i].addEventListener("change", toggleRewardField);
  }
  // Check if no radio button is initially selected
  var checked = Array.from(statusElements).some(function (element) {
    return element.checked;
  });
  if (!checked) {
    toggleRewardField();
  }
});
</script>

app/views/items/show.html.erb
<h1 class="custom-h1 text-center mt-4 mb-3"> Potential Matches </h1>

<%# display the map %>

<div class="row mb-5 flex-column align-items-center border-styling-show">
  <%# <div class="card index-card-bordered col-xs-3 mb-3 px-0"> %>
      <div class="map-styling-showpage col-md-3 card index-card-bordered mb-3 px-0"
      data-controller="showmap"
      data-showmap-markers-value="<%= @markers.to_json %>"
      data-showmap-marker-value="<%= @marker.to_json %>"
      data-showmap-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  <%# </div> %>

  <div class="card index-card-bordered col-xs-3 mb-3 mt-3 px-0">
    <!-- Display lost item -->
    <div class="card-header d-flex justify-content-between align-items-center">
      <% if @item.status == 0 %>
        <h5 class="card-title card-title-bold text-lost-colour mb-0">Lost <%= @item.name %></h5>
      <% else %>
        <h5 class="card-title card-title-bold text-found-colour mb-0">Found <%= @item.name %></h5>
      <% end %>
      <div class="card-icons">
        <% if current_user != @item.user %>
          <a href="#" class="message-icon"><i class="fa-solid fa-message mx-2" style="color: $custom-orange;
  font-size: 20px"></i></a>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6 text-center">
          <p><strong>Date:</strong> <%= @item.date.strftime("%B %d, %Y") %></p>
          <p><strong>Location:</strong> <%= @item.location %></p>
          <% if @item.reward.present? %>
            <p><strong>Reward:</strong> $<%= @item.reward %></p>
          <% end %>
        </div>
        <div class="col-md-6 text-center">
          <% if @item.image.attached? %>
            <%= image_tag @item.image, class: "card-image img-fluid" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
  <% @potential_matches.each do |item| %>
    <div class="card index-card-bordered col-xs-3 mb-3 px-0">
      <!-- Display Found item -->
   <div class="card-header d-flex justify-content-between align-items-center">
  <% if @item.status == 1 %>
    <h5 class="card-title card-title-bold text-lost-colour m-3">Lost <%= item.name %></h5>
  <% else %>
    <h5 class="card-title card-title-bold text-found-colour m-3">Found <%= item.name %></h5>
  <% end %>
  <div class="card-icons">
    <div class="text-right">
      <%= link_to chatroom_path(other_user_id: item.user.id), class: "message-icon" do %>
        <i class="fa-solid fa-message" style="color: #d74b0f; font-size: 20px"></i>
      <% end %>
    </div>
  </div>
</div>

      <div class="card-body">
        <div class="row">
          <div class="col-md-6 text-center">
            <p><strong>Date:</strong> <%= item.date.strftime("%B %d, %Y") %></p>
            <p><strong>Location:</strong> <%= item.location %></p>
            <% if item.reward.present? %>
              <p><strong>Reward:</strong> $<%= item.reward %></p>
            <% end %>
          </div>
          <div class="col-md-6 text-center">
            <% if item.image.attached? %>
              <%= image_tag item.image, class: "card-image img-fluid" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" type="image/x-icon" href="<%= asset_path('favicon.ico') %>" />
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <script src="https://kit.fontawesome.com/5a112b412b.js" crossorigin="anonymous"></script>

    <title>Refinder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

<body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <div class="page-height-setter">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
</body>


</html>

app/views/messages/_message.html.erb
<% def format_timestamp(timestamp) %>
  <% formatted_time = timestamp.strftime("%b %-dth %I:%M %p") %>
  <%= formatted_time %>
<% end %>

<div id="message-<%= message.id %>" class="message <%= message.user == current_user ? 'message-right' : 'message-left' %>">
  <p><strong><%= message.user.email.split("@").first %>:</strong> <span class="timestamp"><%= format_timestamp(message.created_at) %></span></p>

  <p><%== message.body %></p>
</div>

app/views/pages/home.html.erb
<html>
<head>
<%# <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> %>

<style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: white;
    }
    .main-container {
      max-width: 960px;
      margin: 0 auto;
      padding: 20px;
      text-align: center;
    }
    .image-container {
      margin-top: 20px;
      padding-bottom: 10px;
    }
    .responsive-image {
      max-width: 100%;
      height: auto;
      border-radius: 5%;
    }
    .button {
      margin-top: 20px;

    }

    .text-center {
        padding-top: 10px; /* Adjust the value as per your preference */
    }

     .btn-primary {
          height: 40px;
          width: 250px;
          font-size: large;
        background-color: #D65A31;
        color: #EEEEEE;
        border-radius: 10px;
        border-style: solid;
        border-color: #EEEEEE;
        transition: background-color 0.3s ease;
        font-family: 'Courier New', Courier, monospace;
    }

    .btn :hover {
      background-color: #EEEEEE;
        color: #D65A31;
    }

  </style>

</head>


<body>

<div class= "main-container"></div>

<h1 class="custom-header">Refinder</h1>
    <div class="image-container d-flex justify-content-center align-items-center">
      <img src="<%= asset_path('landing.png') %>" alt="Image" class="responsive-image">
    </div>
    <div class="text-center mb-3">
            <%= link_to "Find your lost item!", items_path, class: "btn btn-primary mt-5" %>
   </div>
</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="sticky-bottom">
    <div class="navbar footer navbar-expand-sm navbar-light navbar-lewagon icon-spacing">

      <div class="custom-container">
          <%= link_to root_path, class: "navbar-brand"  do %>
            <i class="fa-solid fa-house" style= "font-size: 25px;"></i>
          <% end %>

        <%= link_to chatrooms_path, class: "navbar-brand"  do %>
          <i class="fa-solid fa-comment" style= "font-size: 25px;"></i>
        <% end %>

          <%= link_to my_items_path, class: "navbar-brand" do %>
            <i class="fa-solid fa-user" style= "font-size: 25px;"></i>
          <% end %>
    </div>
</div>